name: pu_matrix_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - rdkit
  - transformers       # 用于 ChemBERTa 大模型
  - scikit-learn
  - umap-learn         # 用于流形潜在空间可视化
  - pandas
  - numpy
  - scipy
  - tqdm
